/** Starter achievement definitions seeded into the DB. */
export const STARTER_ACHIEVEMENTS = [
  {
    name: 'First Steps',
    description: 'Complete your first typing test',
    category: 'milestone',
    criteria: JSON.stringify({ type: 'tests_completed', value: 1 }),
    badgeIcon: 'footprints',
    points: 10,
    rarity: 'common',
  },
  {
    name: 'Getting Warm',
    description: 'Complete 10 typing tests',
    category: 'milestone',
    criteria: JSON.stringify({ type: 'tests_completed', value: 10 }),
    badgeIcon: 'flame',
    points: 25,
    rarity: 'common',
  },
  {
    name: 'Half Century',
    description: 'Complete 50 typing tests',
    category: 'milestone',
    criteria: JSON.stringify({ type: 'tests_completed', value: 50 }),
    badgeIcon: 'trophy',
    points: 75,
    rarity: 'rare',
  },
  {
    name: 'Century Club',
    description: 'Hit 100 WPM on any test',
    category: 'speed',
    criteria: JSON.stringify({ type: 'best_wpm', value: 100 }),
    badgeIcon: 'zap',
    points: 100,
    rarity: 'epic',
  },
  {
    name: 'Speed Demon',
    description: 'Hit 120 WPM on any test',
    category: 'speed',
    criteria: JSON.stringify({ type: 'best_wpm', value: 120 }),
    badgeIcon: 'rocket',
    points: 150,
    rarity: 'legendary',
  },
  {
    name: 'Sharpshooter',
    description: 'Achieve 98%+ accuracy on a test',
    category: 'accuracy',
    criteria: JSON.stringify({ type: 'best_accuracy', value: 98 }),
    badgeIcon: 'target',
    points: 50,
    rarity: 'rare',
  },
  {
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    category: 'consistency',
    criteria: JSON.stringify({ type: 'streak', value: 7 }),
    badgeIcon: 'calendar',
    points: 80,
    rarity: 'epic',
  },
  {
    name: 'Daily Challenger',
    description: 'Complete a daily challenge',
    category: 'milestone',
    criteria: JSON.stringify({ type: 'daily_challenge', value: 1 }),
    badgeIcon: 'star',
    points: 40,
    rarity: 'rare',
  },
] as const;
