/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypingTestRouteImport } from './routes/typing-test'
import { Route as TestRouteImport } from './routes/test'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PlayRouteImport } from './routes/play'
import { Route as MultiplayerRouteImport } from './routes/multiplayer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as MultiplayerIndexRouteImport } from './routes/multiplayer.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PlayModeRouteImport } from './routes/play.$mode'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as MultiplayerRoomRoomIdRouteImport } from './routes/multiplayer.room.$roomId'
import { Route as AuthSsoCallbackRouteImport } from './routes/auth/sso/callback'

const TypingTestRoute = TypingTestRouteImport.update({
  id: '/typing-test',
  path: '/typing-test',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerRoute = MultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRoute,
} as any)
const MultiplayerIndexRoute = MultiplayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MultiplayerRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayModeRoute = PlayModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => PlayRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const MultiplayerRoomRoomIdRoute = MultiplayerRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => MultiplayerRoute,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/auth/sso/callback',
  path: '/auth/sso/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/daily': typeof DailyRoute
  '/guides': typeof GuidesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/multiplayer': typeof MultiplayerRouteWithChildren
  '/play': typeof PlayRouteWithChildren
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/typing-test': typeof TypingTestRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/play/$mode': typeof PlayModeRoute
  '/u/$username': typeof UUsernameRoute
  '/guides/': typeof GuidesIndexRoute
  '/multiplayer/': typeof MultiplayerIndexRoute
  '/play/': typeof PlayIndexRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/multiplayer/room/$roomId': typeof MultiplayerRoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/daily': typeof DailyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/typing-test': typeof TypingTestRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/play/$mode': typeof PlayModeRoute
  '/u/$username': typeof UUsernameRoute
  '/guides': typeof GuidesIndexRoute
  '/multiplayer': typeof MultiplayerIndexRoute
  '/play': typeof PlayIndexRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/multiplayer/room/$roomId': typeof MultiplayerRoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/daily': typeof DailyRoute
  '/guides': typeof GuidesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/multiplayer': typeof MultiplayerRouteWithChildren
  '/play': typeof PlayRouteWithChildren
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/typing-test': typeof TypingTestRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/play/$mode': typeof PlayModeRoute
  '/u/$username': typeof UUsernameRoute
  '/guides/': typeof GuidesIndexRoute
  '/multiplayer/': typeof MultiplayerIndexRoute
  '/play/': typeof PlayIndexRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/multiplayer/room/$roomId': typeof MultiplayerRoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/contact'
    | '/daily'
    | '/guides'
    | '/leaderboard'
    | '/login'
    | '/multiplayer'
    | '/play'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/settings'
    | '/terms'
    | '/test'
    | '/typing-test'
    | '/guides/$slug'
    | '/play/$mode'
    | '/u/$username'
    | '/guides/'
    | '/multiplayer/'
    | '/play/'
    | '/auth/sso/callback'
    | '/multiplayer/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/contact'
    | '/daily'
    | '/leaderboard'
    | '/login'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/settings'
    | '/terms'
    | '/test'
    | '/typing-test'
    | '/guides/$slug'
    | '/play/$mode'
    | '/u/$username'
    | '/guides'
    | '/multiplayer'
    | '/play'
    | '/auth/sso/callback'
    | '/multiplayer/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/contact'
    | '/daily'
    | '/guides'
    | '/leaderboard'
    | '/login'
    | '/multiplayer'
    | '/play'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/settings'
    | '/terms'
    | '/test'
    | '/typing-test'
    | '/guides/$slug'
    | '/play/$mode'
    | '/u/$username'
    | '/guides/'
    | '/multiplayer/'
    | '/play/'
    | '/auth/sso/callback'
    | '/multiplayer/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ContactRoute: typeof ContactRoute
  DailyRoute: typeof DailyRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MultiplayerRoute: typeof MultiplayerRouteWithChildren
  PlayRoute: typeof PlayRouteWithChildren
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  TestRoute: typeof TestRoute
  TypingTestRoute: typeof TypingTestRoute
  UUsernameRoute: typeof UUsernameRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typing-test': {
      id: '/typing-test'
      path: '/typing-test'
      fullPath: '/typing-test'
      preLoaderRoute: typeof TypingTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer': {
      id: '/multiplayer'
      path: '/multiplayer'
      fullPath: '/multiplayer'
      preLoaderRoute: typeof MultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/multiplayer/': {
      id: '/multiplayer/'
      path: '/'
      fullPath: '/multiplayer/'
      preLoaderRoute: typeof MultiplayerIndexRouteImport
      parentRoute: typeof MultiplayerRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$mode': {
      id: '/play/$mode'
      path: '/$mode'
      fullPath: '/play/$mode'
      preLoaderRoute: typeof PlayModeRouteImport
      parentRoute: typeof PlayRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/multiplayer/room/$roomId': {
      id: '/multiplayer/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/multiplayer/room/$roomId'
      preLoaderRoute: typeof MultiplayerRoomRoomIdRouteImport
      parentRoute: typeof MultiplayerRoute
    }
    '/auth/sso/callback': {
      id: '/auth/sso/callback'
      path: '/auth/sso/callback'
      fullPath: '/auth/sso/callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface MultiplayerRouteChildren {
  MultiplayerIndexRoute: typeof MultiplayerIndexRoute
  MultiplayerRoomRoomIdRoute: typeof MultiplayerRoomRoomIdRoute
}

const MultiplayerRouteChildren: MultiplayerRouteChildren = {
  MultiplayerIndexRoute: MultiplayerIndexRoute,
  MultiplayerRoomRoomIdRoute: MultiplayerRoomRoomIdRoute,
}

const MultiplayerRouteWithChildren = MultiplayerRoute._addFileChildren(
  MultiplayerRouteChildren,
)

interface PlayRouteChildren {
  PlayModeRoute: typeof PlayModeRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayModeRoute: PlayModeRoute,
  PlayIndexRoute: PlayIndexRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ContactRoute: ContactRoute,
  DailyRoute: DailyRoute,
  GuidesRoute: GuidesRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MultiplayerRoute: MultiplayerRouteWithChildren,
  PlayRoute: PlayRouteWithChildren,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  TestRoute: TestRoute,
  TypingTestRoute: TypingTestRoute,
  UUsernameRoute: UUsernameRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
